scrape_configs:
  - job_name: 'spring-boot-app'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'  # Chemin correct pour les métriques Prometheus
    static_configs:
      - targets: ['localhost:8081']
